import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = (process.argv[2] === 'production');

const buildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        ...builtins
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    platform: 'node',
    minify: prod,
    plugins: []  // Removed the custom resolver as it's not needed
};

if (prod) {
    esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
    esbuild.context(buildOptions).then(context => {
        context.watch();
    }).catch(() => process.exit(1));
}